/**
 * UserService
 * UserService is an API that intended to work with users, user credentials and achievements. 
 *
 * OpenAPI spec version: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserRequest { 
    /**
     * User global unique identifier.
     */
    id?: string;
    /**
     * User mail.
     */
    email: string;
    /**
     * User login.
     */
    login: string;
    /**
     * First name of a user.
     */
    firstName: string;
    /**
     * Last name of a user.
     */
    lastName: string;
    /**
     * Last name of a user.
     */
    middleName?: string;
    /**
     * User status.
     */
    status?: string;
    /**
     * User password.
     */
    password: string;
    /**
     * Mark whether the user is an administrator.
     */
    isAdmin: boolean;
    /**
     * Mark whether the user is an active.
     */
    isActive: boolean;
    /**
     * File global unique identifier.
     */
    avatarFileId?: string;
}