/**
 * UserService
 * UserService is an API that intended to work with users, user credentials and achievements. 
 *
 * OpenAPI spec version: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface User { 
    /**
     * User global unique identifier.
     */
    id?: string;
    /**
     * First name of a user.
     */
    firstName?: string;
    /**
     * Last name of a user.
     */
    lastName?: string;
    /**
     * Last name of a user.
     */
    middleName?: string;
    /**
     * User mail.
     */
    email?: string;
    /**
     * User status.
     */
    status?: string;
    /**
     * File global unique identifier.
     */
    avatarFileId?: string;
    /**
     * Mark whether the user is an administrator.
     */
    isAdmin?: boolean;
    /**
     * Certificate files global unique identifiers.
     */
    certificatesIds?: Array<string>;
    /**
     * Certificate files global unique identifiers.
     */
    achievementsIds?: Array<string>;
}