/**
 * UserService
 * UserService is an API intended to work with the users, user profile, achivments  **Changes since 0.0.0** - 
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserAchievementResponse { 
    /**
     * Achievement global unique identifier.
     */
    achievementId?: string;
    /**
     * Time to get the achievement.
     */
    time?: Date;
}