#!/bin/sh
# husky

# Created by Husky v4.3.0 (https://github.com/typicode/husky#readme)
#   At: 19.03.2021, 17:24:00
#   From: undefined (https://github.com/typicode/husky#readme)

. "$(dirname "$0")/husky.sh"
