/**
 * CompanyService
 * CompanyService is an API intended to work with the positions, companies, dep  **Changes since 0.0.0** -
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { EditUserPositionRequest } from '../model/editUserPositionRequest';
import { UserPositionRequest } from '../model/userPositionRequest';
import { UserPositionResponse } from '../model/userPositionResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class UserPositionService {

    protected basePath = 'https://localhost:9815/CompanyService';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * Adds a new position for user.
     * @param body 
     * @param userId User global unique identifier.
     * @param positionId Position global unique identifier.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public addPositionForUserPost(body: UserPositionRequest, userId: string, positionId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public addPositionForUserPost(body: UserPositionRequest, userId: string, positionId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public addPositionForUserPost(body: UserPositionRequest, userId: string, positionId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public addPositionForUserPost(body: UserPositionRequest, userId: string, positionId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling addPositionForUserPost.');
        }

        if (userId === null || userId === undefined) {
            throw new Error('Required parameter userId was null or undefined when calling addPositionForUserPost.');
        }

        if (positionId === null || positionId === undefined) {
            throw new Error('Required parameter positionId was null or undefined when calling addPositionForUserPost.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (userId !== undefined && userId !== null) {
            queryParameters = queryParameters.set('userId', <any>userId);
        }
        if (positionId !== undefined && positionId !== null) {
            queryParameters = queryParameters.set('positionId', <any>positionId);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/addPositionForUser`,
            {
                body: body,
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Deletes the specified position of user.
     * @param userId User global unique identifier.
     * @param positionId Position global unique identifier.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public disableUserPositionDelete(userId: string, positionId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public disableUserPositionDelete(userId: string, positionId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public disableUserPositionDelete(userId: string, positionId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public disableUserPositionDelete(userId: string, positionId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (userId === null || userId === undefined) {
            throw new Error('Required parameter userId was null or undefined when calling disableUserPositionDelete.');
        }

        if (positionId === null || positionId === undefined) {
            throw new Error('Required parameter positionId was null or undefined when calling disableUserPositionDelete.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (userId !== undefined && userId !== null) {
            queryParameters = queryParameters.set('userId', <any>userId);
        }
        if (positionId !== undefined && positionId !== null) {
            queryParameters = queryParameters.set('positionId', <any>positionId);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/disableUserPosition`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Edits a specified position of user.
     * @param body 
     * @param userId User global unique identifier.
     * @param positionId Position global unique identifier.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public editUserPositionPut(body: EditUserPositionRequest, userId: string, positionId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public editUserPositionPut(body: EditUserPositionRequest, userId: string, positionId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public editUserPositionPut(body: EditUserPositionRequest, userId: string, positionId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public editUserPositionPut(body: EditUserPositionRequest, userId: string, positionId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling editUserPositionPut.');
        }

        if (userId === null || userId === undefined) {
            throw new Error('Required parameter userId was null or undefined when calling editUserPositionPut.');
        }

        if (positionId === null || positionId === undefined) {
            throw new Error('Required parameter positionId was null or undefined when calling editUserPositionPut.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (userId !== undefined && userId !== null) {
            queryParameters = queryParameters.set('userId', <any>userId);
        }
        if (positionId !== undefined && positionId !== null) {
            queryParameters = queryParameters.set('positionId', <any>positionId);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('put',`${this.basePath}/editUserPosition`,
            {
                body: body,
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Returns all added positions of specifed user.
     * @param userId User global unique identifier.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getUserPositionsGet(userId: string, observe?: 'body', reportProgress?: boolean): Observable<Array<UserPositionResponse>>;
    public getUserPositionsGet(userId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<UserPositionResponse>>>;
    public getUserPositionsGet(userId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<UserPositionResponse>>>;
    public getUserPositionsGet(userId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (userId === null || userId === undefined) {
            throw new Error('Required parameter userId was null or undefined when calling getUserPositionsGet.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (userId !== undefined && userId !== null) {
            queryParameters = queryParameters.set('userId', <any>userId);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<UserPositionResponse>>('get',`${this.basePath}/getUserPositions`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
