/**
 * FileService
 * FileService is an API intended to work with files.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface FileResponse { 
    /**
     * File global unique identifier.
     */
    id?: string;
    /**
     * File name.
     */
    name?: string;
    /**
     * File content.
     */
    content?: string;
    /**
     * File extension.
     */
    extension?: string;
}