import { OperationResultResponseUserResponse } from '@api/user-service/models/operation-result-response-user-response';
import { setProperty } from '@app/utils/utils';
import { UserInfo } from '@api/user-service/models/user-info';
import { UserAdditionInfo } from '@api/user-service/models/user-addition-info';
import { ImageInfo } from '@api/user-service/models/image-info';
import { UserStatus } from '@api/user-service/models/user-status';
import { CommunicationInfo } from '@api/user-service/models/communication-info';
import { CompanyInfo } from '@api/user-service/models/company-info';
import { DepartmentInfo } from '@api/user-service/models/department-info';
import { OfficeInfo } from '@api/user-service/models/office-info';
import { PositionInfo } from '@api/user-service/models/position-info';
import { RoleInfo } from '@api/user-service/models/role-info';
import { CertificateInfo } from '@api/user-service/models/certificate-info';
import { EducationInfo } from '@api/user-service/models/education-info';
import { ProjectInfo } from '@api/user-service/models/project-info';

export class User implements UserInfo, UserAdditionInfo {
	avatar?: null | ImageInfo;
	firstName?: string;
	id?: string;
	isActive?: boolean;
	isAdmin?: boolean;
	lastName?: string;
	middleName?: null | string;
	status?: UserStatus;
	communications?: null | Array<CommunicationInfo>;
	about?: null | string;
	businessHoursFromUtc?: null | string;
	businessHoursToUtc?: null | string;
	dateOfBirth?: null | string;
	genderName?: null | string;
	latitude?: null | number;
	longitude?: null | number;
	company?: CompanyInfo;
	department?: DepartmentInfo;
	office?: OfficeInfo;
	position?: PositionInfo;
	role?: RoleInfo;
	images?: Array<ImageInfo>;
	certificates?: Array<CertificateInfo>;
	educations?: Array<EducationInfo>;
	projects?: Array<ProjectInfo>;
	skills?: Array<string>;

	constructor(data: OperationResultResponseUserResponse) {
		this.avatar = data.body?.user?.avatar;
		this.firstName = data.body?.user?.firstName;
		this.id = data.body?.user?.id;
		this.isActive = data.body?.user?.isActive;
		this.isAdmin = data.body?.user?.isAdmin;
		this.lastName = data.body?.user?.lastName;
		this.middleName = data.body?.user?.middleName;
		this.status = data.body?.user?.status;
		this.communications = data.body?.user?.communications;
		this.about = data.body?.userAddition?.about;
		this.businessHoursFromUtc = data.body?.userAddition?.businessHoursFromUtc;
		this.businessHoursToUtc = data.body?.userAddition?.businessHoursToUtc;
		this.dateOfBirth = data.body?.userAddition?.dateOfBirth;
		this.genderName = data.body?.userAddition?.genderName;
		this.latitude = data.body?.userAddition?.latitude;
		this.longitude = data.body?.userAddition?.longitude;
		this.company = data.body?.company;
		this.department = data.body?.department;
		this.office = data.body?.office;
		this.position = data.body?.position;
		this.role = data.body?.role;
		this.images = data.body?.images;
		this.certificates = data.body?.certificates;
		this.educations = data.body?.educations;
		this.projects = data.body?.projects;
		this.skills = data.body?.skills;
	}
}
