/**
 * ProjectService
 * This specification describes which endpoints this service has, which models it uses.  This service, ProjectService, is intended to work with the projects -- create them, assign people to them, update info.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ProjectWorkerRequest } from '../model/projectWorkerRequest';
import { ProjectWorkerResponse } from '../model/projectWorkerResponse';
import { WorkersUsersIds } from '../model/workersUsersIds';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ProjectWorkerService {

    protected basePath = 'https://localhost:9803/ProjectService';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * Adding new workers to the project.
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public addNewWorkersToProjectPost(body: ProjectWorkerRequest, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public addNewWorkersToProjectPost(body: ProjectWorkerRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public addNewWorkersToProjectPost(body: ProjectWorkerRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public addNewWorkersToProjectPost(body: ProjectWorkerRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling addNewWorkersToProjectPost.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/addNewWorkersToProject`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Deletes the specified users.
     * @param workersUsersIds User global unique identifier.(GUID)
     * @param projectId Project global unique identifier. (GUID)
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public disableWorkersInProjectDelete(workersUsersIds: WorkersUsersIds, projectId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public disableWorkersInProjectDelete(workersUsersIds: WorkersUsersIds, projectId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public disableWorkersInProjectDelete(workersUsersIds: WorkersUsersIds, projectId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public disableWorkersInProjectDelete(workersUsersIds: WorkersUsersIds, projectId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (workersUsersIds === null || workersUsersIds === undefined) {
            throw new Error('Required parameter workersUsersIds was null or undefined when calling disableWorkersInProjectDelete.');
        }

        if (projectId === null || projectId === undefined) {
            throw new Error('Required parameter projectId was null or undefined when calling disableWorkersInProjectDelete.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (workersUsersIds !== undefined && workersUsersIds !== null) {
            queryParameters = queryParameters.set('WorkersUsersIds', <any>workersUsersIds);
        }
        if (projectId !== undefined && projectId !== null) {
            queryParameters = queryParameters.set('projectId', <any>projectId);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/disableWorkersInProject`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Edits workers associated with a specific project.
     * @param body 
     * @param projectId Project global unique identifier. (GUID)
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public editProjectWorkersByProjectIdPut(body: ProjectWorkerRequest, projectId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public editProjectWorkersByProjectIdPut(body: ProjectWorkerRequest, projectId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public editProjectWorkersByProjectIdPut(body: ProjectWorkerRequest, projectId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public editProjectWorkersByProjectIdPut(body: ProjectWorkerRequest, projectId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling editProjectWorkersByProjectIdPut.');
        }

        if (projectId === null || projectId === undefined) {
            throw new Error('Required parameter projectId was null or undefined when calling editProjectWorkersByProjectIdPut.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (projectId !== undefined && projectId !== null) {
            queryParameters = queryParameters.set('projectId', <any>projectId);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('put',`${this.basePath}/editProjectWorkersByProjectId`,
            {
                body: body,
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Search workers associated with a specific project.
     * @param projectId Project global unique identifier. (GUID)
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getProjectWorkersByProjectIdGet(projectId: string, observe?: 'body', reportProgress?: boolean): Observable<ProjectWorkerResponse>;
    public getProjectWorkersByProjectIdGet(projectId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ProjectWorkerResponse>>;
    public getProjectWorkersByProjectIdGet(projectId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ProjectWorkerResponse>>;
    public getProjectWorkersByProjectIdGet(projectId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (projectId === null || projectId === undefined) {
            throw new Error('Required parameter projectId was null or undefined when calling getProjectWorkersByProjectIdGet.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (projectId !== undefined && projectId !== null) {
            queryParameters = queryParameters.set('projectId', <any>projectId);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ProjectWorkerResponse>('get',`${this.basePath}/getProjectWorkersByProjectId`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
