/**
 * CheckRightsService
 * This specification describes which endpoints this service has, which models it uses.  This service, CheckRightsService, is intended to work with the user rights -- create them, assign them to people, remove.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RightResponse { 
    id?: number;
    name?: string;
    description?: string;
}