/**
 * TimeManagementService
 * TimeManagement is an API intended to work with the time - 
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface EditWorkTimeRequest { 
    /**
     * WorkTime id
     */
    id?: string;
    /**
     * Users working on the current project.
     */
    workerUserId?: string;
    /**
     * Start date task execution.
     */
    startTime?: Date;
    /**
     * Task finish deadline.
     */
    endTime?: Date;
    /**
     * Short description of the task
     */
    title?: string;
    /**
     * The specify project's Id.
     */
    projectId?: string;
    /**
     * Description for alloted time.
     */
    description?: string;
}