export enum Icons {
	/**
	 * Sidebar icons
	 */
	News = 'news',
	TimeTrack = 'time-track',
	Projects = 'projects',
	Users = 'users',
	Departments = 'departments',
	Company = 'company',
	Administration = 'administration',

	/**
	 * Sort icons
	 */
	AlphabetSortAsc = 'alphabet-sort-asc',
	AlphabetSortDesc = 'alphabet-sort-desc',

	/**
	 * Regular icons
	 */
	AccessAlarm = 'access-alarm',
	AccountBalance = 'account-balance',
	Add = 'add',
	Archive = 'archive',
	ArrowDown = 'arrow-down',
	ArrowDownV1 = 'arrow-down-v1',
	ArrowDownV2 = 'arrow-down-v2',
	ArrowUp = 'arrow-up',
	ArrowUpV1 = 'arrow-up-v1',
	ArrowUpV2 = 'arrow-up-v2',
	Attachment = 'attachment',
	Cached = 'cached',
	Calendar = 'calendar',
	CheckCircle = 'check-circle',
	Circle = 'circle',
	Clock = 'clock',
	Close = 'close',
	Delete = 'delete',
	Done = 'done',
	Download = 'download',
	Edit = 'edit',
	EmailRead = 'email-read',
	Favourite = 'favourite',
	FavouriteBorder = 'favourite-border',
	Folder = 'folder',
	Go = 'go',
	HelpOutline = 'help-outline',
	History = 'history',
	InfoOutline = 'info-outline',
	KebabMenu = 'kebab-menu',
	KeyboardArrowLeft = 'keyboard-arrow-left',
	KeyboardArrowRight = 'keyboard-arrow-right',
	Loyalty = 'loyalty',
	Office = 'office',
	PermIdentity = 'perm-identity',
	Photo = 'photo',
	Search = 'search',
	SelfImprovement = 'self-improvement',
	Sick = 'sick',
	Smile = 'smile',
	StarBorder = 'star-border',
	StarFill = 'star-fill',
	Status = 'status',
	SupervisorAccount = 'supervisor-account',
	TextDoc = 'text-doc',
	Unarchive = 'unarchive',
	Vacation = 'vacation',
	ViewHeadline = 'view-headline',
	ViewModule = 'view-module',
	Visibility = 'visibility',
	VisibilityOff = 'visibility-off',
	WorkHome = 'work-home',
}

export const IconPaths = {
	/**
	 * Sidebar icons
	 */
	[Icons.News]: '/assets/icons/sidebar/news.svg',
	[Icons.TimeTrack]: '/assets/icons/sidebar/time-track.svg',
	[Icons.Projects]: '/assets/icons/sidebar/projects.svg',
	[Icons.Users]: '/assets/icons/sidebar/users.svg',
	[Icons.Departments]: '/assets/icons/sidebar/departments.svg',
	[Icons.Company]: '/assets/icons/sidebar/company.svg',
	[Icons.Administration]: '/assets/icons/sidebar/settings.svg',

	/**
	 * Sort icons
	 */
	[Icons.AlphabetSortAsc]: '/assets/icons/alphabet-sort-asc.svg',
	[Icons.AlphabetSortDesc]: '/assets/icons/alphabet-sort-desc.svg',

	/**
	 * Regular icons
	 */
	[Icons.AccessAlarm]: '/assets/icons/access-alarm.svg',
	[Icons.AccountBalance]: '/assets/icons/account-balance.svg',
	[Icons.Add]: '/assets/icons/add.svg',
	[Icons.Archive]: '/assets/icons/archive.svg',
	[Icons.ArrowDown]: '/assets/icons/arrow-down.svg',
	[Icons.ArrowDownV1]: '/assets/icons/arrow-down-v1.svg',
	[Icons.ArrowDownV2]: '/assets/icons/arrow-down-v2.svg',
	[Icons.ArrowUp]: '/assets/icons/arrow-up.svg',
	[Icons.ArrowUpV1]: '/assets/icons/arrow-up-v1.svg',
	[Icons.ArrowUpV2]: '/assets/icons/arrow-up-v2.svg',
	[Icons.Attachment]: '/assets/icons/attachment.svg',
	[Icons.Cached]: '/assets/icons/cached.svg',
	[Icons.Calendar]: '/assets/icons/calendar.svg',
	[Icons.CheckCircle]: '/assets/icons/check-circle.svg',
	[Icons.Circle]: '/assets/icons/circle.svg',
	[Icons.Clock]: '/assets/icons/clock.svg',
	[Icons.Close]: '/assets/icons/close.svg',
	[Icons.Delete]: '/assets/icons/delete.svg',
	[Icons.Done]: '/assets/icons/done.svg',
	[Icons.Download]: '/assets/icons/download.svg',
	[Icons.Edit]: '/assets/icons/edit.svg',
	[Icons.EmailRead]: '/assets/icons/email-read.svg',
	[Icons.Favourite]: '/assets/icons/favourite.svg',
	[Icons.FavouriteBorder]: '/assets/icons/favourite-border.svg',
	[Icons.Folder]: '/assets/icons/folder.svg',
	[Icons.Go]: '/assets/icons/go.svg',
	[Icons.HelpOutline]: '/assets/icons/help-outline.svg',
	[Icons.History]: '/assets/icons/history.svg',
	[Icons.InfoOutline]: '/assets/icons/info-outline.svg',
	[Icons.KebabMenu]: '/assets/icons/kebab-menu.svg',
	[Icons.KeyboardArrowLeft]: '/assets/icons/keyboard-arrow-left.svg',
	[Icons.KeyboardArrowRight]: '/assets/icons/keyboard-arrow-right.svg',
	[Icons.Loyalty]: '/assets/icons/loyalty.svg',
	[Icons.Office]: '/assets/icons/office.svg',
	[Icons.PermIdentity]: '/assets/icons/perm-identity.svg',
	[Icons.Photo]: '/assets/icons/photo.svg',
	[Icons.Search]: '/assets/icons/search.svg',
	[Icons.SelfImprovement]: '/assets/icons/self-improvement.svg',
	[Icons.Sick]: '/assets/icons/sick.svg',
	[Icons.Smile]: '/assets/icons/smile.svg',
	[Icons.StarBorder]: '/assets/icons/star-border.svg',
	[Icons.StarFill]: '/assets/icons/star-fill.svg',
	[Icons.Status]: '/assets/icons/status.svg',
	[Icons.SupervisorAccount]: '/assets/icons/supervisor-account.svg',
	[Icons.TextDoc]: '/assets/icons/text-doc.svg',
	[Icons.Unarchive]: '/assets/icons/unarchive.svg',
	[Icons.Vacation]: '/assets/icons/vacation.svg',
	[Icons.ViewHeadline]: '/assets/icons/view-headline.svg',
	[Icons.ViewModule]: '/assets/icons/view-module.svg',
	[Icons.Visibility]: '/assets/icons/visibility.svg',
	[Icons.VisibilityOff]: '/assets/icons/visibility-off.svg',
	[Icons.WorkHome]: '/assets/icons/work-home.svg',
};
