/**
 * CompanyService
 * CompanyService is an API intended to work with the positions, companies, dep  **Changes since 0.0.0** -
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface EditUserPositionRequest { 
    /**
     * The time when the employee started working in the position.
     */
    startTime?: Date;
    /**
     * The time when the employee ended working in the position.
     */
    endTime?: Date;
}