/**
 * TimeManagementService
 * TimeManagement is an API intended to work with the time - 
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface LeaveTimeRequest { 
    /**
     * Users working on the current project.
     */
    workerUserId: string;
    /**
     * Start time leave from task.
     */
    startLeave: Date;
    /**
     * End time leave from task.
     */
    endLeave: Date;
    /**
     * The reason for which lost time.
     */
    leaveType: number;
    /**
     * Description for alloted time.
     */
    comment?: string;
}